import requests

data = {
    "id": 1,
    "dur": 0.1,
    "proto": 6,
    "service": 0,
    "state": 12,
    "spkts": 5,
    "dpkts": 5,
    "sbytes": 1000,
    "dbytes": 500,
    "rate": 0.1,
    "sttl": 32,
    "dttl": 32,
    "sload": 1.2,
    "dload": 0.9,
    "sloss": 0,
    "dloss": 0,
    "sinpkt": 0.01,
    "dinpkt": 0.01,
    "sjit": 0.001,
    "djit": 0.002,
    "swin": 200,
    "stcpb": 0,
    "dtcpb": 0,
    "dwin": 300,
    "tcprtt": 0.01,
    "synack": 0.002,
    "ackdat": 0.002,
    "smean": 100,
    "dmean": 50,
    "trans_depth": 0,
    "response_body_len": 0,
    "ct_srv_src": 1,
    "ct_state_ttl": 2,
    "ct_dst_ltm": 1,
    "ct_src_dport_ltm": 1,
    "ct_dst_sport_ltm": 1,
    "ct_dst_src_ltm": 1,
    "is_ftp_login": 0,
    "ct_ftp_cmd": 0,
    "ct_flw_http_mthd": 0,
    "ct_src_ltm": 1,
    "ct_srv_dst": 1,
    "is_sm_ips_ports": 0
}

response = requests.post("http://127.0.0.1:5000/predict", json=data)

print("Response from server:", response.text)